Djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
import users ,todoListApp

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('users.urls', namespace = 'users')),
    path(r'', include('todoListApp.urls', namespace = 'todoListApp')),

]



djangoapp/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'todoListApp'

urlpatterns = [
    path('tasks/', views.Tasks.as_view(), name='tasks'),
    path('tasks/<int:pk>/delete/', views.Task_Delete.as_view(), name='Task_delete'),
    path('tasks/<int:pk>/update/', views.Task_Update.as_view(), name='Task_update'),
    path('tasks/new/', views.Task_New.as_view(), name='Task_New'),
    ]

users/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
]

djangoapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User




class Task (models.Model):
    STATUS = (('done','DONE'), ('processed', 'PROCESSED'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title= models.CharField(max_length=50,null=False,blank=False)
    description = models.CharField(max_length=200,null = True , blank=True)
    status=models.CharField(choices=STATUS, max_length=10,default='processed')
    date=models.DateField(default=timezone.now)

    def __str__(self):
         return f'{self.date} -> {self.title} : {self.description} / {self.status}' 
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'title'], name='unique_user_task'),
        ] 

users/models.py
from django.db import models

djangoapp/forms.py
from django import forms
from .models import Task


class TaskForm (forms.ModelForm):
    title = forms.CharField(label=" Title ",strip=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}))
    description = forms.CharField(label=" description ",strip=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Description'}))
    status = forms.ChoiceField(choices=Task.STATUS,widget=forms.Select(attrs={'class':'form-control'}))

    class Meta:
        model = Task
        fields = ('title','description','status','date')
        
        widgets={
            'date' : forms.DateInput(attrs={'class':'form-control','type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        
        super(TaskForm, self).__init__(*args, **kwargs)

        for i in self.fields :
            self.fields[i].required = False
        
        self.fields['title'].required = True
        self.fields['status'].required = True
        self.fields['date'].required = True

users/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms


class RegistrationForm (UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','id':'userName','label' : 'userName', 'placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Valid Email is required'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'id':'pwd','label' : 'password','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password'}))
    class Meta:
        model = get_user_model()
        fields = ('username','email','password1', 'password2')
        
class LoginForm(AuthenticationForm):
   username = forms.CharField(widget=forms.TextInput(attrs={'autofocus':True, 'id':'userName','label' : 'userName','placeholder':'Username Here', 'class':'form-control'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'id':'pwd','label' : 'password','placeholder':'********'}))

djangoapp/views.py
from django.shortcuts import render
from .models import Task
from .forms import TaskForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import   CreateView,View,ListView,UpdateView
from django.shortcuts import redirect
from django.utils import timezone

class Tasks(LoginRequiredMixin,ListView):
   template_name = 'tasksList.html'
   model=Task
   login_url = 'users:login'
   context_object_name = 'tasks'
   def get_queryset(self):
      filters={}
      context = super().get_queryset()
      filters['user'] = self.request.user
      if self.request.GET.get("page")== None:
           for key, value in self.request.GET.items():
              print("hello world!")
              print(value)
              if value != '*' and value != '':
                filters[key] = value
           
           new_context = Task.objects.filter(
                   **filters
               )
           return new_context
         
      return context
      
   def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Tasks=Task.objects.all()
        return context

class Task_New(LoginRequiredMixin,CreateView):
    model = Task 
    form_class = TaskForm  
    template_name = 'taskEdit.html'
    login_url = 'users:login'
    success_url = reverse_lazy('todoListApp:tasks') 
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class Task_Update(LoginRequiredMixin,UpdateView):
    model = Task
    template_name = 'taskEdit.html'
    form_class = TaskForm
    login_url = 'users:login'
    success_url = reverse_lazy('todoListApp:tasks') 
    
class Task_Delete(LoginRequiredMixin,View):
    login_url = 'users:login'
    def get(self, request ,pk):
        emp = Task.objects.get(pk=pk)
        emp.delete()
        return redirect('todoListApp:tasks', permanent=True)
  

users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from .forms import LoginForm,RegistrationForm
from django.shortcuts import resolve_url
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import View
from django.views.generic import CreateView
from django.urls import reverse_lazy

class Login_View(LoginView):

    model = get_user_model()
    form_class = LoginForm
    template_name = 'login.html'

    def get_success_url(self):
        url = resolve_url('todoListApp:tasks')
        return url


class Logout_View(View):

    def get(self,request):
        logout(self.request)
        return redirect ('users:login',permanent=True)
 

class Register (CreateView):
    model = get_user_model()
    form_class  = RegistrationForm
    template_name = 'register.html'
    success_url = reverse_lazy('users:login')

djangoapp/templates/taskEdit.html
<!DOCTYPE html>
{% load static %}
<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbs5Ksz04UjcGz5l3wfkW1AqJRpTUU9vpcMf1PiYMjAq4j5g" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="{% static 'taskList.css' %}">
    </head>
<body >
{% if user.is_authenticated %}
   <div class="container">
    <div class="row d-flex justify-content-center ">
        <div class="col-md-8">
          <div class="card-hover-shadow-2x mb-3 card">
            <div class="card-header-tab card-header">
              <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                <i class="fa fa-tasks"></i>
                &nbsp; Tasks
                
             </div>
                  
            </div>
            <div class="container-fluid">
              
                <div style="position: static;" class="ps ps--active-y">
                  <div class="ps-content">
                    <form enctype="multipart/form-data" class="form-group" method="POST">
                      {% csrf_token %}
                      <small class="mb-5">All Fields are required</small>
                          {{form.as_p}}
                          <div class="card-footer d-flex justify-content-end" id="footer">
                          <button class="btn btn-outline-success btn-rounded"><i class="mdi mdi-cloud-download"></i>Submmit</button></button>
                          
                      </div>
                  </form>  
                  </div>
                  
                </div>
           
            </div>
           
          </div>
        </div>
        </div>
    </div>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% endif %}
</body>
</html>

djangoapp/templates/tasksList.html
<!DOCTYPE html>
{% load static %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="{% static 'taskList.css' %}">

  <!-- Bootstrap 4 JavaScript -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

  </head>

<body >
    {% if user.is_authenticated %}
   <div class="container">
    <div class="row ">
      
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">
                <img src="{% static 'userLogo' %}" alt="Admin" class="rounded-circle" width="150">
                <div class="mt-3">
                  <h4>{{user.username}}</h4>
                  <p class="text-secondary mb-1">{{user.email}}</p>
                  <a class="primary" href="{% url 'users:logout' %}">SignOut <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="card-hover-shadow-2x mb-3 card">
            <div class="card-header-tab card-header">
              <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                <i class="fa fa-tasks"></i>
                &nbsp; Tasks
             </div>
                  
            </div>
            <div class="scroll-area-sm">
              <perfect-scrollbar class="ps-show-limits">
                <div style="position: static;" class="ps ps--active-y">
                  <div class="ps-content">
                    <ul class=" list-group list-group-flush">
                    {% for task in tasks %}
                      <li class="list-group-item">
                        <div class="todo-indicator bg-warning"></div>
                        <div class="widget-content p-0">
                          <div class="widget-content-wrapper">
                            <div class="widget-content-left mr-2">
                            
                            </div>
                            <div class="widget-content-left">
                              <div class="widget-heading">{{task.date}} | {{task.title}}  
                              <div class="badge  {% if task.status == 'processed' %}badge-danger{% else %}badge-success{% endif %}  ml-2">
                                {{task.status}}</div>
                          
                              </div>
                              <div class="widget-subheading"><i>
                                {{ task.description }}
                              </i></div>
                             
                            </div>
                          <div class="widget-content-right">
                            <a class="border-0 btn-transition  success " href="{% url 'todoListApp:Task_update' pk=task.pk %}">
                              <i class="fa fa-pencil"></i></a>
                              <a class="border-0 btn-transition danger" href="{% url 'todoListApp:Task_delete' pk=task.pk %}">
                             <i class="fa fa-trash"></i>
                              </a>
                          </div>
                          </div>
                        </div>
                      </li>
                      {% endfor %}  
                    </ul>
                  </div>
                  
                </div>
              </perfect-scrollbar>
            </div>
            <div class="card-footer" id="footer">
                <a class="primary " href="{% url 'todoListApp:Task_New' %}">Add <i class="fa fa-plus"></i></a>
                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter">Filter <i class="fa fa-filter"></i></button>
               

                <!-- Modal -->
                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Filter Options</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <form method="GET">
                        <div class="card-body">
                          <div class="row">
                             <label for="status">STATUS</label><br>
                                <select class="form-control" id="status"  name="status">
                                  <option value="*" selected>Tout</option>
                                  <option name="status" value="done">DONE</option>
                                  <option name="status" value="processed">PROCESSED</option>
                                </select>  
                          </div>
                          <br>
                           <div class="row">
                             <label for="date">DATE</label><br>
                             <input type="date" id="date" name="date" class="form-control" >
                           </div> 
                        </div>
                         <div class="modal-footer">
                        
                          <button type="submit" class="btn btn-primary">Filter</button>
                         </div>
                      </form>
                    </div>
                  </div>
                </div>  
              </div>
            </div>
          </div>
        </div>
    </div>

     {% endif %}
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/log.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mouLj6pPNO8qStVz+p5UZ4pO5Cv18p8I+1G1J6S5g" crossorigin="anonymous">
    <link rel="stylesheet" href="login.css">
</head>

<body>
    <div class="wrapper">
        <div class="text-center mt-4 name">
            TasksApp
        </div>
        <form action=" {% url 'users:login' %} " method="post" class="p-3 mt-3">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                {{form.username}}
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                {{form.password}}
            </div>
            <button type="submit" class="btn mt-3">Login</button>
        </form>
        <div class="text-center fs-6">
            <a href="{% url 'users:register' %}">Sign up</a>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

users/templates/register.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/log.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mouLj6pPNO8qStVz+p5UZ4pO5Cv18p8I+1G1J6S5g" crossorigin="anonymous">

</head>

<body>
    <div class="wrapper">
        <div class="text-center mt-4 name">
            TasksApp
        </div>
        <form method="post" enctype='multipart/form-data' class="p-3 mt-3">
            {% csrf_token %}
            {{form.errors}}
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                {{form.username}}
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                {{form.email}}
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                {{form.password1}}
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                {{form.password2}}
            </div>
            <button type="submit" class="btn mt-3">Submit</button>
        </form>
        <div class="text-center fs-6">
            <a href="{% url 'users:login' %}">Sign in</a>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>